[package]
name = "slog-benchmark"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
slog = "2.4.1"
slog-async = "2.3.0"
slog-json = "2.2.0"
microbench = "0.5.0"
chrono = "0.4.24"
