[package]
name = "native-logging-benchmark"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.17"
microbench = "0.5.0"

[profile.release]
lto = true
